### ISSUE TITLE
Connexion integration does not log service exceptions

### ISSUE THREAD

**Issue by miguelgrinberg** [racker/fleece#38]
If something goes wrong inside an API call invoked by connexion, the stack trace of that error appears to be thrown away and connexion's own 500 error is logged in its place.

For example, this is what goes on the log for a simple `KeyError` exception in one of the Flask routes:

```
500: Internal Server Error: HTTPError
Traceback (most recent call last):
File "/var/task/fleece/xray.py", line 354, in wrapper
metadata_extractor=metadata_extractor,
File "/var/task/fleece/xray.py", line 263, in generic_xray_wrapper
return_value = wrapped(*args, **kwargs)
File "/var/task/handler.py", line 76, in lambda_handler
validate_responses=False)
File "/var/task/fleece/connexion.py", line 227, in call_api
return app.call_api(event)
File "/var/task/fleece/connexion.py", line 116, in call_api
raise httperror.HTTPError(status=response.status_code)
fleece.httperror.HTTPError: 500: Internal Server Error
```

**Comment by larsbutler** [comment]
Hey @miguelgrinberg, I have run into issues here as well. If memory serves, this 500 error is encountered when the response of your endpoint handler does not conform to the contract specified in the Swagger spec. Essentially, it's an automatic "Bad Response" from Connexion.

- Bad request from client --> 400 Bad Request
- Bad response from server --> 500 Internal Server Error

I've tried to [document that in the code a bit](https://github.com/racker/fleece/blob/2d08f25ce581e24c93d57fc228aea3a57fbb7d12/fleece/connexion.py#L107-L110), but it seems to be an issue we all run into at some point anyway. I'll do some digging and see if there's a way to specifically sift out API contract errors from other 500 errors.

**Comment by larsbutler** [comment]
I think I found something I can use. Patch on the way.

**Comment by larsbutler** [comment]
Okay, this should help a bit @miguelgrinberg: https://github.com/racker/fleece/pull/40.

**Comment by miguelgrinberg** [comment]
@larsbutler not sure if this was clear, but in this case I have no control of the response. This particular case occurred because there was a `KeyError` somewhere inside the handler function. Flask will either log the exception and return a 500 response (the default), or if you configure it to bubble up exceptions will let you handle it as you see fit. Not sure what connexion does, but it would be important to preserve and log or raise the original exception.

**Comment by larsbutler** [comment]
@miguelgrinberg I see what you mean. I think the best way to handle that is to add an error handler to the app. Connexion has some docs on how to do that: http://connexion.readthedocs.io/en/latest/exceptions.html. I can add a default error handler (which just logs the exception) to my PR; let me know if that will solve it for you.
