### ISSUE TITLE
from fleece import boto3 hides boto3 features

### ISSUE THREAD

**Issue by ranman** [racker/fleece#39]
```python
from fleece import boto3
session = boto3.session.Session(region_name="us-east-1")
```
Fails:
```
Traceback (most recent call last):
  File "stream.py", line 17, in <module>
    session = boto3.session.Session(region_name="us-east-1")
AttributeError: 'module' object has no attribute 'session'
```

Is there another way to organize fleece so that it doesn't hide or change boto3 behavior?

**Comment by ryandub** [comment]
Meh - that's not good. Thanks for the report - we'll take a look and fix it. cc/ @miguelgrinberg

**Comment by miguelgrinberg** [comment]
Hmm. Yeah, I honestly did not intend this to be a 100% complete wrapper for boto3, just `client()` and `resource()` (as [documented](https://github.com/racker/fleece#boto3-wrappers)). But I guess it makes sense to make it so. Thanks for the report, I'll add the remaining symbols exported by boto3 to our wrapper.

**Comment by ranman** [comment]
The main issue with this is in Lambda functions a lot of people create a session object instead of a client so they don't have to specify the region_name multiple times and so they can overload credentials if needed.

I also see it used in multi threading situations.
