### ISSUE TITLE
Support "partial installs" of fleece

### ISSUE THREAD

**Issue by hwine** [racker/fleece#43]
I'm using fleece to get AWS X-Ray support in AWS lambda services. It works great!

The one challenge is reducing the size of the install. Since I'm only using X-Ray, I don't need any of the heavy weight dependencies, such as Flask. Space is at a premium in the Lambda environment.

I'm assuming manual pruning can be done (I haven't begun the process). However, that may be "not fun" to replicate in ``tox`` or some cloud based CI services.

If support for this use case can be added into the fleece packaging, awesome!  If not, I'll document my results here.

**Comment by ryandub** [comment]
@hwine - I think this is a great idea and have been thinking about this as well. Perhaps we could put some of the heavier stuff behind an extras flag like [requests does](https://github.com/requests/requests/blob/master/setup.py#L95)? Thoughts?

**Comment by hwine** [comment]
I was thinking along those lines, too. But I think that wouldn't be backward compatible. But I'm not that familiar with packaging.

A documented approach maybe sufficient. I haven't experimented yet - maybe just installing with --no-deps would do it. As long as we add some tests to ensure it stays okay. 😁

**Comment by ryandub** [comment]
@hwine - Apologies for the amount of time it took to implement this. #47 should now move most of the heavy deps into an extras package and make the install size much smaller. There should be a new version released in a day or so with these changes.

**Comment by hwine** [comment]
@ryandub no worries! I'll be happy to take the update. Thanks for your work on this!
