### ISSUE TITLE
Allow `fleece build` to exclude files from the `--source` directory

### ISSUE THREAD

**Issue by larsbutler** [racker/fleece#73]
When you build a lambda zip, fleece will pick up everything in the --source directory. If you structure your Python project like the majority of Python projects (with a setup.py and a top level package in the repo root), this is kind of problem because will pick up everything in that directory. The result is that the lambda zip will contain a bunch of stuff that doesn't need to be there (README, CI config, etc.).

Here's an example command:

```bash
$ fleece build --requirements requirements/lambda.txt --python36 --source . . --target lambda_dist
```

In this case, the source dir is `.`. There isn't any obvious way to exclude subsets of file, though perhaps I'm missing something.

Perhaps adding some kind of `--exclude` functionality (maybe even support globs?) would help. Alternatively, being more selective about files/directories would do the trick, e.g.: `fleece build --include foo --include bar/fizz --include config.json --include stuff.yaml`.

**Comment by ryandub** [comment]
@larsbutler - Thanks! I think adding an explicit exclude with glob support would probably be the best start.

**Comment by larsbutler** [comment]
@ryandub 
> Thanks! I think adding an explicit exclude with glob support would probably be the best start.

Agreed, this approach will allow us to workaround the immediate problem.

As a follow-on, we might consider also adding a `--include` flag and deprecating the `--source` flag. The reason for this is that as new files get added to a repo (in the `--source` directory), `fleece build` might accidentally package up something new that we don't want in the zip--and we would need to constantly remember to add new explicit `--exclude` statements. (At best we could end up packaging garbage/unused files into the zip. At worst, we could end packaging sensitive artifacts that shouldn't be in the zip.)

What do you think?

**Comment by miguelgrinberg** [comment]
The `--include` flag is problematic. You can't just point to a random file or directory in your disk and include it, you need to also say where in the lambda directory structure you want it placed. I think the idea of having a source directory makes more sense, and with `--exclude` you can take care of the exceptions. Building a lambda project without the concept of a source directory is extremely more difficult.

**Comment by Gifflen** [comment]
It might end up getting a bit nasty but using a format similar to docker to
include file and specify what and where
maybe --include some/path/file:where/you/want/the/file

**Comment by TimSimpsonR** [comment]
I like the idea of an `--include` flag but I agree with @miguelgrinberg that it could get out of hand since we'd also need to say where in the lambda to put stuff.

So here's a crazy idea: what if we had an optional manifest file fleece could use instead? It could be called `manifest.txt` and contain the same directive fleece uses, as well as a new one to explicitly specify the requirements.txt files we wanted. For most lambdas would look like this:

```
-i src/handler.py:/
-r src/requirements.txt
```

or to include all files in `src`:

```
-i src/:/
-r src/requirements.txt
```

This would also allow us to do other neat things though. Currently I'm using symlinks in a project to reuse code. Using a manifest.txt format we could do this instead:
```
-r src/requirements.txt
-i src/:/
-r ../../common/requirements.txt
-i ../../common/common:/common
```
